---
- name: Install docker keyring
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
    id: 0EBFCD88

- name: Add official docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    state: present
    update_cache: yes
    filename: docker-ce

- name: Create docker override directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Add systemd override
  copy:
    src: override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf

- name: Install docker community edition
  apt:
    name: docker-ce
    state: present

- name: Add user ubuntu to docker group
  user:
    append: yes
    name: ubuntu
    groups: docker
